import logging
import subprocess
import re
from flask import Blueprint, jsonify, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user

from .modem import get_network_info, get_signal, set_apn, reset_modem
from .config import load_config, save_config
from .network import active_wan
from .firewall import apply_firewall
from .speedtest import run_speedtest

web = Blueprint("web", __name__)

@web.route("/login", methods=["GET", "POST"])
def login():
    from .auth import authenticate
    if request.method == "POST":
        u = request.form.get("username", "")
        p = request.form.get("password", "")
        user = authenticate(u, p)
        if user:
            login_user(user)
            logging.info("User %s logged in", u)
            return redirect(url_for("web.dashboard"))
        flash("Credenciales inválidas", "error")
        logging.warning("Failed login attempt for user %s", u)
    return render_template("login.html")

@web.route("/logout")
@login_required
def logout():
    logging.info("User %s logged out", current_user.username)
    logout_user()
    return redirect(url_for("web.login"))

@web.route("/")
@login_required
def dashboard():
    return render_template("dashboard.html", username=current_user.username)

@web.route("/settings")
@login_required
def settings():
    cfg = load_config()
    return render_template("settings.html", cfg=cfg)

@web.route("/api/signal")
@login_required
def api_signal():
    return jsonify(get_signal())

@web.route("/api/modem/info")
@login_required
def api_modem_info():
    return jsonify(get_network_info())

@web.route("/api/modem/reset", methods=["POST"])
@login_required
def api_reset():
    result = reset_modem()
    logging.info("Modem reset requested by %s", current_user.username)
    return jsonify({"ok": True, "response": result})

@web.route("/api/apn", methods=["POST"])
@login_required
def api_set_apn():
    apn = request.json.get("apn", "").strip()
    if not apn:
        return jsonify({"ok": False, "error": "APN vacío"}), 400
    set_apn(apn)
    cfg = load_config()
    cfg["apn"] = apn
    save_config(cfg)
    logging.info("APN updated to %s by %s", apn, current_user.username)
    return jsonify({"ok": True})

@web.route("/api/wan")
@login_required
def api_wan():
    return jsonify({"active": active_wan(), "mode": load_config().get("wan_mode", "auto")})

@web.route("/api/wan", methods=["POST"])
@login_required
def api_set_wan():
    mode = request.json.get("mode", "auto")
    if mode not in ("auto", "eth", "lte"):
        return jsonify({"ok": False, "error": "Modo inválido"}), 400
    cfg = load_config()
    cfg["wan_mode"] = mode
    save_config(cfg)
    logging.info("WAN mode set to %s by %s", mode, current_user.username)
    return jsonify({"ok": True, "mode": mode})

@web.route("/api/security", methods=["POST"])
@login_required
def api_security():
    cfg = load_config()
    sec = cfg.setdefault("security", {})
    sec["isolate_clients"] = bool(request.json.get("isolate_clients", True))
    save_config(cfg)
    
    # Aplicar firewall inmediatamente
    try:
        apply_firewall()
        logging.info("Firewall applied. isolate_clients=%s by %s", sec["isolate_clients"], current_user.username)
        return jsonify({"ok": True})
    except Exception as e:
        logging.error("Error applying firewall: %s", e)
        return jsonify({"ok": False, "error": str(e)}), 500

@web.route("/api/speedtest", methods=["POST"])
@login_required
def api_speedtest():
    """Ejecuta test de velocidad (puede tardar 30-60 segundos)"""
    logging.info("Speedtest iniciado por %s", current_user.username)
    result = run_speedtest()
    return jsonify(result)


# ============== WiFi AP Configuration ==============

def read_hostapd_config():
    """Lee configuracion actual de hostapd"""
    config = {"ssid": "", "password": "", "channel": "6"}
    try:
        with open("/etc/hostapd/hostapd.conf", "r") as f:
            content = f.read()
            
        ssid_match = re.search(r'^ssid=(.+)$', content, re.MULTILINE)
        pass_match = re.search(r'^wpa_passphrase=(.+)$', content, re.MULTILINE)
        chan_match = re.search(r'^channel=(\d+)$', content, re.MULTILINE)
        
        if ssid_match:
            config["ssid"] = ssid_match.group(1).strip()
        if pass_match:
            config["password"] = pass_match.group(1).strip()
        if chan_match:
            config["channel"] = chan_match.group(1).strip()
            
    except FileNotFoundError:
        logging.warning("hostapd.conf not found")
    except Exception as e:
        logging.error("Error reading hostapd config: %s", e)
    
    return config


def write_hostapd_config(ssid, password, channel):
    """Escribe configuracion en hostapd.conf"""
    config_content = f"""# Hostapd configuration - WiFi Access Point
# Auto-generated by RPI Router Panel

interface=wlan0
driver=nl80211
ssid={ssid}
hw_mode=g
channel={channel}
wmm_enabled=0
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase={password}
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
country_code=CL
ieee80211n=1
ieee80211d=1
"""
    
    with open("/etc/hostapd/hostapd.conf", "w") as f:
        f.write(config_content)


@web.route("/api/wifi/config")
@login_required
def api_wifi_config():
    """Obtiene configuracion WiFi actual"""
    config = read_hostapd_config()
    # No enviar password completo por seguridad
    if config["password"]:
        config["password_masked"] = "*" * len(config["password"])
    return jsonify(config)


@web.route("/api/wifi/config", methods=["POST"])
@login_required
def api_wifi_set_config():
    """Guarda configuracion WiFi y reinicia hostapd"""
    data = request.json
    
    ssid = data.get("ssid", "").strip()
    password = data.get("password", "").strip()
    channel = data.get("channel", "6").strip()
    
    # Validaciones
    if not ssid:
        return jsonify({"ok": False, "error": "SSID no puede estar vacio"}), 400
    
    if len(ssid) > 32:
        return jsonify({"ok": False, "error": "SSID muy largo (max 32 caracteres)"}), 400
    
    # Si no se proporciona password, mantener el actual
    if not password:
        current_config = read_hostapd_config()
        password = current_config.get("password", "")
    
    if len(password) < 8:
        return jsonify({"ok": False, "error": "Password debe tener minimo 8 caracteres"}), 400
    
    if len(password) > 63:
        return jsonify({"ok": False, "error": "Password muy largo (max 63 caracteres)"}), 400
    
    if channel not in ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"]:
        return jsonify({"ok": False, "error": "Canal invalido"}), 400
    
    try:
        # Guardar configuracion
        write_hostapd_config(ssid, password, channel)
        logging.info("WiFi config updated: SSID=%s, channel=%s by %s", ssid, channel, current_user.username)
        
        # Reiniciar hostapd
        subprocess.run(["systemctl", "restart", "hostapd"], check=True, timeout=30)
        logging.info("hostapd restarted successfully")
        
        return jsonify({
            "ok": True, 
            "message": "Configuracion guardada. WiFi reiniciado.",
            "ssid": ssid,
            "channel": channel
        })
        
    except subprocess.CalledProcessError as e:
        logging.error("Error restarting hostapd: %s", e)
        return jsonify({"ok": False, "error": "Error al reiniciar WiFi. Revisa los logs."}), 500
    except Exception as e:
        logging.error("Error saving WiFi config: %s", e)
        return jsonify({"ok": False, "error": str(e)}), 500
